config/routes.rb
Wildgarden::Application.routes.draw do

  resources :plants
  get 'main/index'

  root :to => 'main#index'

end

app/models/plant.rb
class Plant < ActiveRecord::Base
  attr_accessible :description, :latin_name, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  def index
    @plants = Plant.find(:all)
  end

 def new
   @plant = Plant.new
 end
 
 def show
   @plant = Plant.find(params[:id])
 end
 
 def create
   plant = Plant.new(params[:plant])
   plant.save
   redirect_to plants_path
 end
 
 def destroy
   plant = Plant.find(params[:id])
   plant.delete
   redirect_to plants_path
 end
 
 def edit
   @plant = Plant.find(params[:id])
 end
 
 def update
   @plant = Plant.find(params[:id])
   @plant.update_attributes(params[:plant])
   redirect_to plant_path(@plant)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Wildgarden</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="container">
			<div id="navigation_menu">
				<ul>
					<li>
						<%= link_to 'Noveny hozzaadasa', new_plant_path %>
					</li>
					<li>
						<%= link_to 'Novenyek listaja', plants_path %>
					</li>
				</ul>
			</div>
			<div id="main">
				<%= yield %>
			</div>
			<div id="footer">
				<p>
					<%= link_to 'Vissza', :back %>
				</p>
			</div>
		</div>
	</body>
</html>

app/views/main/index.html.erb
<h1>Hello, Wildgarden!</h1>

app/views/plants/edit.html.erb
<h3>Növény módosítása</h3>
<%= form_for(@plant) do |p| %>
<div class="field">
	<%= p.text_field :name %>
	<%= p.label 'Nev' %>
</div>
<div class="field">
	<%= p.text_field :latin_name %>
	<%= p.label 'Latin nev' %>
</div>
<div class="field">
	<%= p.text_area :description %>
	<%= p.label 'Leiras' %>
</div>
<div class="field_actions">
	<%= p.submit 'Modositas' %>
</div>
<% end %>

app/views/plants/index.html.erb
<h3>Novenyek</h3>
<% @plants.each do |plant| %>
	<p><%= link_to plant.name, plant_path(plant) %>, <%= plant.latin_name %> 
		<%= link_to 'Torles', plant_path(plant), :method => 'delete' %>
		<%= link_to 'Modositas', edit_plant_path(plant) %>
		</p>
<% end %>

app/views/plants/new.html.erb
<h3>Novenyek hozzaadasa</h3>
<%= form_for(@plant) do |p| %>
<div class="field">
	<%= p.text_field :name %>
	<%= p.label 'Nev' %>
</div>
<div class="field">
	<%= p.text_field :latin_name %>
	<%= p.label 'Latin nev' %>
</div>
<div class="field">
	<%= p.text_area :description %>
	<%= p.label 'Leiras' %>
</div>
<div class="field_actions">
	<%= p.submit 'Felvetel' %>
</div>
<% end %>

app/views/plants/show.html.erb
<p>Nev: <%= @plant.name %></p>
<p>Latin nev: <%= @plant.latin_name %></p>
<p>Leiras: <%= @plant.description %></p>